services:
  bombsquad_gui_release:
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile
      args:
        - cmake_build_type=Release
        - headless_build=0
    image: bombsquad_gui_release:${VERSION:-latest}
    platform: linux/amd64
    ports:
      - "43210:43210"
    labels:
      - bombsquad_version=${VERSION:-latest}
      - bombsquad_build=${BUILD_NUMBER:-unknown}
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse:/run/user/1000/pulse
      - ${HOME}/.ballisticakit:/root/.ballisticakit
    devices:
      - /dev/snd:/dev/snd
    privileged: true

  bombsquad_gui_debug:
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile
      args:
        - cmake_build_type=Debug
        - headless_build=0
    image: bombsquad_gui_debug:${VERSION:-latest}
    platform: linux/amd64
    ports:
      - "43210:43210"
    labels:
      - bombsquad_version=${VERSION:-latest}
      - bombsquad_build=${BUILD_NUMBER:-unknown}
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse:/run/user/1000/pulse
      - ${HOME}/.ballisticakit:/root/.ballisticakit
    devices:
      - /dev/snd:/dev/snd
    privileged: true

  bombsquad_server_release:
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile
      args:
        - cmake_build_type=Release
        - headless_build=1
    image: bombsquad_server_release:${VERSION:-latest}
    platform: linux/amd64
    ports:
      - "43210:43210"
    labels:
      - bombsquad_version=${VERSION:-latest}
      - bombsquad_build=${BUILD_NUMBER:-unknown}

  bombsquad_server_debug:
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile
      args:
        - cmake_build_type=Debug
        - headless_build=1
    image: bombsquad_server_debug:${VERSION:-latest}
    platform: linux/amd64
    ports:
      - "43210:43210"
    labels:
      - bombsquad_version=${VERSION:-latest}
      - bombsquad_build=${BUILD_NUMBER:-unknown}