when:
  - event: push
  - event: pull_request
  - event: cron
    cron: ci

steps:
  - name: check
    image: codeberg.org/3ra/ballistica-dev:latest
    pull: true
    commands:
      - make env
      - BA_PCOMMANDBATCH_BUILD_REQUIRE=1 make check
