when:
  - event: push
  - event: pull_request
  - event: cron
    cron: ci

steps:
  - name: test
    image: codeberg.org/3ra/ballistica-dev:latest
    pull: true
    commands:
      - make env
      - tools/spinoff fset-copy template_fs poo
      - make update
      - make cmake-modular-server-build
      - cd build/cmake/modular-server-debug/staged/dist && PYTHONPATH=ba_data/python ./ballisticakit_headless -c "import baenv; baenv.configure(); import bapoo; print(bapoo)"
