when:
  - event: push
  - event: pull_request
  - event: cron
    cron: ci

steps:
  - name: test
    image: codeberg.org/3ra/ballistica-dev:latest
    pull: true
    commands:
      - make env
      - make spinoff-test-core
      - make spinoff-test-base
