when:
  - event: tag
    ref: refs/tags/v*

steps:
  - name: build
    image: codeberg.org/3ra/ballistica:latest
    pull: true
    commands:
      - make prefab-linux-x86-64-gui-debug-build
      - mv -v build/prefab/full/linux_x86_64_gui/debug build/prefab/full/linux_x86_64_gui/ballisticakit_linux_x86_64_debug
      - tar cvzfC ballisticakit_linux_x86_64_debug.tar.xz build/prefab/full/linux_x86_64_gui ballisticakit_linux_x86_64_debug
  - name: publish
    image: woodpeckerci/plugin-release
    settings:
      api_key:
        from_secret: ACCESS_TOKEN
      files:
        - 'ballisticakit_linux_x86_64.tar.xz'
      title: ${CI_COMMIT_TAG}
    depends_on: [build]
