name: TEST

on:
  push:

jobs:
  release_docker_gui_debug_image_amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Setup project environment
      run: make env
    - name: Docker login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }} 
    - name: Make the build
      run: |
        make docker-server-release
        make docker-save
    # - name: Zip the build
    #   run: zip -j bombsquad_docker_gui_debug.tar.zip build/docker/bombsquad_gui_debug_docker.tar
    # - name: Upload the build
    #   uses: ncipollo/release-action@v1
    #   with:
    #     body : "See the [Full Changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)"
    #     allowUpdates: true
    #     artifacts: bombsquad_docker_gui_debug.tar.zip
    - name: Push to github image repository
      run: |
        docker tag bombsquad_server_release:latest ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_server:release_${{ github.ref_name }}_amd64
        docker push ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_server:release_${{ github.ref_name }}_amd64

  release_docker_gui_debug_image_arm64:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Setup project environment
      run: make env
    - name: Docker login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }} 
    - name: Make the build
      run: |
        make docker-arm64-server-release
        make docker-save
    # - name: Zip the build
    #   run: zip -j bombsquad_docker_gui_debug.tar.zip build/docker/bombsquad_gui_debug_docker.tar
    # - name: Upload the build
    #   uses: ncipollo/release-action@v1
    #   with:
    #     body : "See the [Full Changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)"
    #     allowUpdates: true
    #     artifacts: bombsquad_docker_gui_debug.tar.zip
    - name: Push to github image repository
      run: |
        docker tag bombsquad_server_release:latest ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_server:release_${{ github.ref_name }}_arm64
        docker push ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_server:release_${{ github.ref_name }}_arm64

  manifest-docker-multiarch:
    needs: [release_docker_gui_debug_image_amd64 , release_docker_gui_debug_image_arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest
        run: |
          docker manifest create ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_server:release_latest \
            --amend ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_server:release_${{ github.ref_name }}_amd64 \
            --amend ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_server:release_${{ github.ref_name }}_arm64
          docker manifest push ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_server:release_latest
